### ISSUE TITLE
useState inside of custom sortFunction causes infinite rerenders

### ISSUE THREAD

**Issue by joey80** [jbetancur/react-data-table-component#1045]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
In my project i'm trying to track the 'state' of the table data when a sort has happened so I can update other components that are tied to the data. I created a callback in my parent component to fire when the custom sortFunction is ran so it could update the parent with the newly sorted rows. This setState causes infinite rerenders in my actual project, however in the Code Sandbox example I put together I get a different error: 'Warning: Cannot update a component (`App`) while rendering a different component (`Unknown`). To locate the bad setState() call inside `Unknown` ...'

## To Reproduce
See Code Sandbox example

## Expected behavior
The callback should fire without causing multiple rerenders

## Code Sandbox, Screenshots, or Relevant Code
https://codesandbox.io/embed/youthful-field-nyor27

## Versions (please complete the following information)
 - React 17.0.2
 - Styled Components 5.3.5
 - OS: Windows 10
 - Browser Chrome

**Comment by jbetancur** [comment]
You should use the onSort callback. Injecting serState into a sort callback is going to cause that sort of issue.

**Comment by joey80** [comment]
@jbetancur How would I get the sorted data from the onSort callback? I thought it just returns the column name, id, etc and sort direction?

**Comment by jbetancur** [comment]
I think I misunderstood. That's an interesting use case. There's no way to currently do that easily though. It's possible however, as a feature we could have onSort return the sorted data as a third parameter.

**Comment by joey80** [comment]
That would be a great addition to onSort. I did find a workaround to get rid of the error but its not ideal. I wrapped my callback in the customSortFunction in a setTimeout to make sure RDT has finished updating

```
setTimeout(() => onSortCallback(sortedRows), 0);
```

**Comment by jbetancur** [comment]
I've implemented this in 7.5.1

**Comment by joey80** [comment]
@jbetancur Thank you for that, that was really quick. When do new releases get published? I'm looking forward to trying this out.

**Comment by jbetancur** [comment]
Np. It's available as 7.5.1

**Comment by joey80** [comment]
Hmm I'm still seeing 7.5.0 on npm
https://www.npmjs.com/package/react-data-table-component

**Comment by Milan-VLIZ** [comment]
Hi,

Just to note that this might have messed up using useState inside onSort function.
I took the liberty to fork the above mentioned sandbox with a very basic example: https://codesandbox.io/s/react-data-table-forked-8c3psr?file=/src/index.js
If you try to order any column it gets stuck in a loop due to the useState in handleSort function.
When reverting to 7.5.0 the problem does not occur.

Hope this helps identify the problem.

Kind regards,
Milan

**Comment by jbetancur** [comment]
@Milan-VLIZ Nice catch. 7.5.2 with a fix incoming

**Comment by clemich** [comment]
Hello,

Is it possible to disable the sorting function?

Many thanks
